'use client';
import { Spinner } from '@/components/design/primitives';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Bell, CheckCheck, Loader2 } from 'lucide-react';
import { SellerLayout } from '@/components/seller/seller-layout';
import { auth } from '@/lib/firebase';
type Notification = { id: string; title?: string; message?: string; type?: string; href?: string; createdAt?: number; readAt?: number };
export default function SellerNotificationsPage() { const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const request = async (method = 'GET', body?: unknown) => { const token = await auth.currentUser?.getIdToken(); return fetch('/api/seller/notifications', { method, headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), Authorization: `Bearer ${token || ''}` }, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' }); }; const load = async () => { try { const response = await request(); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.notifications || []); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []); const mark = async (id?: string) => { await request('PATCH', id ? { id } : { all: true }); await load(); }; return <SellerLayout><div className="flex items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Notifications</h1><p className="mt-1 text-sm text-foreground-muted">Account, verification, catalog, and support updates.</p></div><button onClick={() => mark()} className="inline-flex min-h-10 items-center gap-2 ac-content-panel px-3 text-xs font-semibold"><CheckCheck className="h-4 w-4" />Mark all read</button></div><div className="mt-7 overflow-hidden ac-content-panel">{loading ? <div className="flex justify-center p-10"><Spinner className="h-6 w-6 animate-spin" /></div> : items.length === 0 ? <div className="p-10 text-center"><Bell className="mx-auto h-8 w-8 text-foreground-muted" /><p className="mt-3 text-sm text-foreground-muted">No notifications yet.</p></div> : <div className="divide-y divide-border">{items.map(item => <Link key={item.id} href={item.href || '/seller/dashboard'} onClick={() => { if (!item.readAt) void mark(item.id); }} className={`block p-5 transition hover:bg-secondary/40 ${item.readAt ? '' : 'bg-accent/5'}`}><div className="flex gap-3"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${item.readAt ? 'bg-border' : 'bg-accent'}`} /><div><h2 className="font-semibold">{item.title || 'Seller update'}</h2><p className="mt-1 text-sm leading-6 text-foreground-muted">{item.message}</p><div className="mt-2 text-xs text-foreground-muted">{item.createdAt ? new Date(item.createdAt).toLocaleString() : ''}</div></div></div></Link>)}</div>}</div></SellerLayout>; }
