'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { onValue, ref } from 'firebase/database';
import { ArrowLeft, BarChart3, MailCheck, TrendingUp, UserMinus } from 'lucide-react';
import { AdminLayout } from '@/components/admin/admin-layout';
import { db } from '@/lib/firebase';

const values = <T,>(value: unknown) => value && typeof value === 'object' ? Object.values(value as Record<string, T>) : [];
export default function NewsletterAnalyticsPage() {
  const [subscribers, setSubscribers] = useState<any[]>([]); const [campaigns, setCampaigns] = useState<any[]>([]); const [events, setEvents] = useState<any[]>([]);
  useEffect(() => { const cleanups = [onValue(ref(db, 'newsletterSubscribers'), s => setSubscribers(values(s.val()))), onValue(ref(db, 'newsletterCampaigns'), s => setCampaigns(values(s.val()))), onValue(ref(db, 'newsletterDeliveryEvents'), s => setEvents(values(s.val())))]; return () => cleanups.forEach(fn => fn()); }, []);
  const metrics = useMemo(() => { const active = subscribers.filter(item => item.active && !item.suppressed).length; const unsubscribed = subscribers.filter(item => item.unsubscribedAt).length; const pending = subscribers.filter(item => item.pendingConfirmation).length; const sent = campaigns.reduce((sum, item) => sum + Number(item.sent || 0), 0); const failed = campaigns.reduce((sum, item) => sum + Number(item.failed || 0), 0); const delivered = events.filter(item => item.type === 'delivered').length; const bounced = events.filter(item => item.type === 'bounced').length; const complained = events.filter(item => item.type === 'complained').length; return { active, unsubscribed, pending, sent, failed, bounced, complained, deliveryRate: sent ? Math.round((delivered || Math.max(0, sent - failed)) / sent * 100) : 0, unsubscribeRate: subscribers.length ? Number((unsubscribed / subscribers.length * 100).toFixed(1)) : 0 }; }, [subscribers, campaigns, events]);
  const months = useMemo(() => { const result: Record<string, { joined: number; left: number }> = {}; for (let index = 5; index >= 0; index--) { const date = new Date(); date.setMonth(date.getMonth() - index); result[date.toISOString().slice(0, 7)] = { joined: 0, left: 0 }; } subscribers.forEach(item => { const joined = item.confirmedAt || item.subscribedAt; const left = item.unsubscribedAt; if (joined && result[new Date(joined).toISOString().slice(0, 7)]) result[new Date(joined).toISOString().slice(0, 7)].joined++; if (left && result[new Date(left).toISOString().slice(0, 7)]) result[new Date(left).toISOString().slice(0, 7)].left++; }); return Object.entries(result); }, [subscribers]);
  const max = Math.max(1, ...months.flatMap(([, value]) => [value.joined, value.left]));
  return <AdminLayout><div className="space-y-6"><div><Link href="/admin/newsletter" className="mb-4 inline-flex items-center gap-2 text-sm text-foreground-muted hover:text-foreground"><ArrowLeft className="h-4 w-4" />Newsletter Manager</Link><h1 className="text-3xl font-semibold tracking-tight">Newsletter Analytics</h1><p className="mt-2 text-sm text-foreground-muted">Live audience growth, campaign delivery, unsubscribe, bounce, and complaint health.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={TrendingUp} label="Active subscribers" value={metrics.active} note={`${metrics.pending} pending confirmation`} /><Metric icon={MailCheck} label="Delivery rate" value={`${metrics.deliveryRate}%`} note={`${metrics.sent} sent · ${metrics.failed} failed`} /><Metric icon={UserMinus} label="Unsubscribe rate" value={`${metrics.unsubscribeRate}%`} note={`${metrics.unsubscribed} unsubscribed`} /><Metric icon={BarChart3} label="List health" value={metrics.bounced + metrics.complained} note={`${metrics.bounced} bounced · ${metrics.complained} complained`} /></div><section className="ac-content-panel p-6"><h2 className="font-semibold">Audience movement</h2><p className="mt-1 text-xs text-foreground-muted">Confirmed subscriptions and unsubscribes over the last six months.</p><div className="mt-8 grid h-64 grid-cols-6 items-end gap-3 sm:gap-6">{months.map(([month, value]) => <div key={month} className="flex h-full flex-col justify-end"><div className="flex flex-1 items-end justify-center gap-1"><div title={`${value.joined} joined`} className="w-1/2 rounded-t-md bg-accent" style={{ height: `${Math.max(value.joined ? 8 : 2, value.joined / max * 100)}%` }} /><div title={`${value.left} left`} className="w-1/2 rounded-t-md bg-red-400" style={{ height: `${Math.max(value.left ? 8 : 2, value.left / max * 100)}%` }} /></div><div className="mt-3 text-center text-[10px] font-medium text-foreground-muted">{new Date(`${month}-02`).toLocaleDateString(undefined, { month: 'short' })}</div></div>)}</div><div className="mt-4 flex justify-center gap-5 text-xs text-foreground-muted"><span><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-sm bg-accent" />Joined</span><span><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-sm bg-red-400" />Unsubscribed</span></div></section></div></AdminLayout>;
}
function Metric({ icon: Icon, label, value, note }: { icon: typeof TrendingUp; label: string; value: string | number; note: string }) { return <div className="ac-content-panel p-5"><Icon className="h-5 w-5 text-accent" /><div className="mt-4 text-2xl font-semibold">{value}</div><div className="mt-1 text-sm font-medium">{label}</div><div className="mt-1 text-xs text-foreground-muted">{note}</div></div>; }
