'use client';
import { Spinner } from '@/components/design/primitives';
import { FormEvent, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { CheckCircle2, Loader2, SlidersHorizontal } from 'lucide-react';
import { SiteLayout } from '@/components/site/site-layout';

const TOPICS = [{ key: 'company', label: 'Company updates' }, { key: 'sourcing', label: 'Sourcing and procurement' }, { key: 'sellers', label: 'Seller opportunities' }, { key: 'suppliers', label: 'Supplier partnerships' }] as const;
export default function PreferencesPage() {
  const token = useSearchParams().get('token') || '';
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState(''); const [email, setEmail] = useState('');
  const [frequency, setFrequency] = useState('weekly'); const [topics, setTopics] = useState<Record<string, boolean>>({ company: true, sourcing: true, sellers: true, suppliers: true });
  useEffect(() => { void (async () => { try { const response = await fetch('/api/newsletter/preferences', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'load', token }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load preferences.'); setEmail(data.emailMasked || ''); setFrequency(data.frequency || 'weekly'); setTopics(data.topics || {}); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load preferences.'); } finally { setLoading(false); } })(); }, [token]);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const response = await fetch('/api/newsletter/preferences', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'save', token, frequency, topics }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to save preferences.'); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save preferences.'); } finally { setSaving(false); } };
  return <SiteLayout><main className="min-h-[72vh] px-5 py-16 sm:py-24"><div className="mx-auto max-w-xl"><div className="text-center"><SlidersHorizontal className="mx-auto h-8 w-8 text-accent" /><h1 className="mt-5 text-3xl font-semibold tracking-tight">Newsletter preferences</h1><p className="mt-3 text-sm leading-6 text-foreground-muted">Choose how often and what kind of Auronix Commerce updates you receive{email ? ` at ${email}` : ''}.</p></div><div className="mt-8 rounded-[28px] border border-border bg-card p-6 shadow-premium sm:p-8">{loading ? <div className="flex justify-center py-12"><Spinner className="h-7 w-7 animate-spin text-accent" /></div> : error && !email ? <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-700 dark:text-red-300">{error}</div> : <form onSubmit={save}><fieldset><legend className="font-semibold">Email frequency</legend><div className="mt-3 grid gap-2">{[['weekly', 'Weekly digest'], ['monthly', 'Monthly summary'], ['important_only', 'Important announcements only']].map(([value, label]) => <label key={value} className={`flex cursor-pointer gap-3 rounded-xl border p-3.5 ${frequency === value ? 'border-accent bg-accent/5' : 'border-border'}`}><input type="radio" checked={frequency === value} onChange={() => setFrequency(value)} /><span className="text-sm font-medium">{label}</span></label>)}</div></fieldset><fieldset className="mt-7"><legend className="font-semibold">Topics</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{TOPICS.map(topic => <label key={topic.key} className="flex cursor-pointer items-center gap-3 rounded-xl border border-border p-3.5"><input type="checkbox" checked={topics[topic.key] === true} onChange={event => setTopics(current => ({ ...current, [topic.key]: event.target.checked }))} /><span className="text-sm">{topic.label}</span></label>)}</div></fieldset>{saved && <div className="mt-5 flex items-center gap-2 rounded-xl border border-green-500/25 bg-green-500/5 p-3 text-sm text-green-700 dark:text-green-300"><CheckCircle2 className="h-4 w-4" />Preferences saved.</div>}{error && <div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-700 dark:text-red-300">{error}</div>}<button disabled={saving} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-primary px-5 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving && <Spinner className="h-4 w-4 animate-spin" />}{saving ? 'Saving…' : 'Save preferences'}</button><Link href={`/newsletter/unsubscribe?token=${encodeURIComponent(token)}`} className="mt-3 block rounded-xl py-2 text-center text-sm font-medium text-foreground-muted hover:text-foreground">Unsubscribe from all newsletters</Link></form>}</div></div></main></SiteLayout>;
}
