'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { BriefcaseBusiness, Clock3, Download, FileArchive, MessageSquareText, Search, Send, ShieldCheck } from 'lucide-react';
import { AdminLayout } from '@/components/admin/admin-layout';
import { Spinner } from '@/components/design/primitives';
import { auth } from '@/lib/firebase';
import { onAuthChange } from '@/lib/auth';
import { userFacingError } from '@/lib/user-facing-error';

async function adminRequest(path = '', init: RequestInit = {}) {
  const user = auth.currentUser; if (!user) throw new Error('Your admin session has expired.');
  const token = await user.getIdToken();
  const response = await fetch(`/api/admin/deal-room${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(init.headers || {}) }, cache: 'no-store' });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'The admin request failed.'); return data;
}
const formatDate = (value: number) => value ? new Date(value).toLocaleString() : '—';

export default function AdminDealRoomsPage() {
  const [rooms, setRooms] = useState<any[]>([]); const [selectedId, setSelectedId] = useState(''); const [detail, setDetail] = useState<any>(null);
  const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [detailLoading, setDetailLoading] = useState(false); const [working, setWorking] = useState(''); const [error, setError] = useState('');
  const [message, setMessage] = useState(''); const [reviewNote, setReviewNote] = useState<Record<string, string>>({});
  const loadRooms = useCallback(async () => { try { const data = await adminRequest(); setRooms(data.rooms || []); if (!selectedId && data.rooms?.[0]) setSelectedId(data.rooms[0].applicationId); } catch (caught) { setError(caught instanceof Error ? userFacingError(caught) : 'Unable to load Deal Rooms.'); } finally { setLoading(false); } }, [selectedId]);
  const loadDetail = useCallback(async (id: string) => { if (!id) return; setDetailLoading(true); try { const data = await adminRequest(`?applicationId=${encodeURIComponent(id)}`); setDetail(data); setError(''); } catch (caught) { setError(caught instanceof Error ? userFacingError(caught) : 'Unable to load this Deal Room.'); } finally { setDetailLoading(false); } }, []);
  useEffect(() => onAuthChange(user => { if (user) loadRooms(); else setLoading(false); }), [loadRooms]);
  useEffect(() => { if (selectedId) loadDetail(selectedId); }, [selectedId, loadDetail]);
  const filtered = useMemo(() => rooms.filter(room => `${room.companyName} ${room.contactName} ${room.contactEmail} ${room.applicationId} ${room.status}`.toLowerCase().includes(query.toLowerCase())), [rooms, query]);
  const refresh = async () => { await Promise.all([loadRooms(), selectedId ? loadDetail(selectedId) : Promise.resolve()]); };
  const sendMessage = async () => { if (!message.trim() || !selectedId) return; setWorking('message'); try { await adminRequest('', { method: 'POST', body: JSON.stringify({ action: 'message', applicationId: selectedId, message }) }); setMessage(''); await refresh(); } catch (caught) { setError(caught instanceof Error ? userFacingError(caught) : 'Message failed.'); } finally { setWorking(''); } };
  const reviewDocument = async (documentId: string, status: string) => { setWorking(documentId); try { await adminRequest('', { method: 'PATCH', body: JSON.stringify({ action: 'document-review', applicationId: selectedId, documentId, status, note: reviewNote[documentId] || '' }) }); await refresh(); } catch (caught) { setError(caught instanceof Error ? userFacingError(caught) : 'Document review failed.'); } finally { setWorking(''); } };
  const download = async (document: any) => { try { const token = await auth.currentUser?.getIdToken(); const response = await fetch(`/api/deal-room/files?applicationId=${encodeURIComponent(selectedId)}&documentId=${encodeURIComponent(document.id)}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Download failed.'); const url = URL.createObjectURL(await response.blob()); const link = window.document.createElement('a'); link.href = url; link.download = document.name; link.click(); URL.revokeObjectURL(url); } catch (caught) { setError(caught instanceof Error ? userFacingError(caught) : 'Download failed.'); } };

  const room = detail?.room;
  return <AdminLayout><div className="space-y-6"><header className="ac-workspace-hero"><div><span className="ac-eyebrow"><BriefcaseBusiness className="h-4 w-4" /> Partner operations</span><h1>Deal Rooms</h1><p>Review private commercial terms, authorization documents, messages, and application history in one place.</p></div><div className="ac-kpi-strip"><span><strong>{rooms.length}</strong>rooms</span><span><strong>{rooms.reduce((count, item) => count + (item.documents?.filter((doc: any) => doc.status === 'pending').length || 0), 0)}</strong>documents waiting</span></div></header>{error && <div className="ac-alert ac-alert-error">{error}</div>}
    {loading ? <div className="ac-content-panel flex min-h-[360px] items-center justify-center"><Spinner className="h-7 w-7" /></div> : <div className="ac-admin-deal-grid"><aside className="ac-content-panel ac-deal-index"><label className="ac-index-search"><Search className="h-4 w-4" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Business, contact, ID…" /></label><div>{filtered.map(item => <button key={item.applicationId} className={selectedId === item.applicationId ? 'is-active' : ''} onClick={() => setSelectedId(item.applicationId)}><strong>{item.companyName || 'Unnamed business'}</strong><span>{item.contactName || item.contactEmail}</span><small>{String(item.status || 'pending').replace(/_/g, ' ')} · {item.documents?.length || 0} docs</small></button>)}{!filtered.length && <p className="p-5 text-sm text-foreground-muted">No matching partner records.</p>}</div></aside>
      <main>{detailLoading ? <div className="ac-content-panel flex min-h-[420px] items-center justify-center"><Spinner className="h-7 w-7" /></div> : room ? <div className="space-y-6"><section className="ac-content-panel p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="ac-eyebrow">{room.status}</span><h2 className="mt-2 text-2xl font-semibold">{room.companyName}</h2><p className="mt-1 text-sm text-foreground-muted">{room.contactName} · {room.contactEmail} · {room.applicationId}</p></div><a className="ac-button ac-button-secondary" href={`/admin/sellers?application=${encodeURIComponent(room.applicationId)}`}>Open application</a></div><div className="ac-commercial-readout mt-6">{[['Brands', room.commercial.brands], ['MOQ', room.commercial.minimumOrderQuantity], ['Pricing', room.commercial.pricingModel], ['Currency', room.commercial.currency], ['Lead time', room.commercial.leadTimeDays ? `${room.commercial.leadTimeDays} days` : ''], ['Incoterms', room.commercial.incoterms]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || 'Not supplied'}</strong></div>)}</div>{room.commercial.notes && <p className="mt-5 rounded-2xl bg-background/40 p-4 text-sm">{room.commercial.notes}</p>}</section>
        <section className="ac-content-panel p-6"><Heading icon={ShieldCheck} title="Document decisions" text="Approve, reject, expire, or archive each private file with a review note." /><div className="mt-5 grid gap-4">{room.documents.length ? room.documents.map((doc: any) => <article className="ac-admin-document" key={doc.id}><div className="ac-admin-document-head"><FileArchive className="h-5 w-5" /><div><strong>{doc.name}</strong><span>{doc.type.replace(/-/g, ' ')} · {(doc.size / 1024 / 1024).toFixed(1)} MB · {formatDate(doc.uploadedAt)}</span></div><em data-status={doc.status}>{doc.status}</em><button onClick={() => download(doc)}><Download className="h-4 w-4" />Download</button></div><textarea value={reviewNote[doc.id] ?? doc.reviewNote ?? ''} onChange={(e) => setReviewNote({ ...reviewNote, [doc.id]: e.target.value })} placeholder="Decision note visible to the partner…" /><div className="flex flex-wrap gap-2"><button onClick={() => reviewDocument(doc.id, 'approved')} disabled={!!working}>Approve</button><button onClick={() => reviewDocument(doc.id, 'rejected')} disabled={!!working}>Reject</button><button onClick={() => reviewDocument(doc.id, 'expired')} disabled={!!working}>Mark expired</button><button onClick={() => reviewDocument(doc.id, 'archived')} disabled={!!working}>Archive</button>{working === doc.id && <Spinner className="h-4 w-4" />}</div></article>) : <Empty text="No private documents have been submitted." />}</div></section>
        {detail.history?.length > 0 && <section className="ac-content-panel p-6"><Heading icon={Clock3} title="Revision comparison" text="Field-by-field changes are preserved for every applicant resubmission." /><div className="mt-5 grid gap-3">{detail.history.map((revision: any) => <details className="ac-revision" key={revision.id}><summary><strong>Revision {revision.revision}</strong><span>{revision.reason?.replace(/-/g, ' ')} · {formatDate(revision.createdAt)}</span></summary>{revision.fieldChanges?.length ? <div>{revision.fieldChanges.map((change: any) => <article key={change.field}><span>{change.label}</span><del>{change.before || 'Empty'}</del><ins>{change.after || 'Empty'}</ins></article>)}</div> : <p>Initial submitted application snapshot.</p>}</details>)}</div></section>}
        <div className="grid gap-6 xl:grid-cols-2"><section className="ac-content-panel p-6"><Heading icon={MessageSquareText} title="Partner messages" text="Every message stays with the application." /><div className="ac-message-list mt-5">{room.messages.length ? room.messages.map((item: any) => <div key={item.id} className={`ac-message ${item.senderRole === 'admin' ? 'is-own' : ''}`}><span>{item.senderRole === 'admin' ? 'Auronix team' : room.contactName} · {formatDate(item.createdAt)}</span><p>{item.body}</p></div>) : <Empty text="No conversation yet." />}</div><textarea className="mt-4 min-h-[95px] w-full rounded-2xl border border-border p-3" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Send a review update…" /><button className="ac-button mt-3" onClick={sendMessage} disabled={!message.trim() || !!working}>{working === 'message' ? <Spinner className="h-4 w-4" /> : <Send className="h-4 w-4" />}Send and notify</button></section>
        <section className="ac-content-panel p-6"><Heading icon={Clock3} title="Application history" text="Status, field edits, messages, documents, and notifications." /><div className="ac-timeline mt-5">{room.timeline.length ? room.timeline.map((item: any) => <article key={item.id}><i /><div><strong>{item.title}</strong><time>{formatDate(item.createdAt)}</time><p>{item.description}</p>{item.fieldChanges?.map((change: any) => <small key={change.field}>{change.label}: {change.before || 'Empty'} → {change.after || 'Empty'}</small>)}</div></article>) : <Empty text="No timeline events yet." />}</div></section></div>
      </div> : <div className="ac-content-panel p-10 text-center text-foreground-muted">Choose a partner record.</div>}</main></div>}
  </div></AdminLayout>;
}

function Heading({ icon: Icon, title, text }: { icon: any; title: string; text: string }) { return <div className="flex items-start gap-3"><span className="ac-section-icon"><Icon className="h-5 w-5" /></span><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-foreground-muted">{text}</p></div></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-border p-5 text-center text-sm text-foreground-muted">{text}</p>; }
