'use client';
import { Spinner } from '@/components/design/primitives';
import { useEffect, useState } from 'react';
import { Laptop, Loader2, RefreshCw, ShieldCheck, Smartphone, XCircle } from 'lucide-react';
import { AdminLayout } from '@/components/admin/admin-layout';
import { auth } from '@/lib/firebase';
type Session = { id: string; device?: string; userAgent?: string; createdAt?: number; lastSeenAt?: number; expiresAt?: number; revokedAt?: number };
export default function SecurityPage() {
  const [sessions, setSessions] = useState<Session[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/admin/sessions', { headers: { Authorization: `Bearer ${token || ''}` }, cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load sessions.'); setSessions(Object.values(data.sessions || {}).sort((a: any, b: any) => Number(b.lastSeenAt || 0) - Number(a.lastSeenAt || 0)) as Session[]); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load sessions.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const revoke = async (id: string) => { setBusy(id); try { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/admin/sessions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token || ''}` }, body: JSON.stringify({ id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to revoke session.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to revoke session.'); } finally { setBusy(''); } };
  return <AdminLayout><div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-accent"><ShieldCheck className="h-4 w-4" />Admin protection</div><h1 className="mt-3 text-3xl font-semibold tracking-tight">Security & Sessions</h1><p className="mt-2 text-sm text-foreground-muted">Review two-factor verified devices and revoke sessions you do not recognize.</p></div><button onClick={load} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 ac-content-panel px-4 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div><div className="rounded-2xl border border-green-500/25 bg-green-500/5 p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-green-600" /><div><h2 className="font-semibold text-green-700 dark:text-green-300">Two-factor session protection enabled</h2><p className="mt-1 text-sm leading-6 text-foreground-muted">New admin sign-ins require a time-limited email security code when ADMIN_MFA_SECRET is configured.</p></div></div></div>{error && <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-700 dark:text-red-300">{error}</div>}<section className="ac-content-panel"><div className="border-b border-border p-5"><h2 className="font-semibold">Verified sessions</h2></div>{loading ? <div className="flex justify-center p-10"><Spinner className="h-6 w-6 animate-spin" /></div> : <div className="divide-y divide-border">{sessions.map(session => { const mobile = /mobile|android|iphone/i.test(`${session.device} ${session.userAgent}`); return <div key={session.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-secondary">{mobile ? <Smartphone className="h-5 w-5" /> : <Laptop className="h-5 w-5" />}</span><div className="min-w-0 flex-1"><div className="font-medium">{session.device || 'Browser session'}</div><div className="mt-1 text-xs text-foreground-muted">Last active {session.lastSeenAt ? new Date(session.lastSeenAt).toLocaleString() : 'unknown'} · Expires {session.expiresAt ? new Date(session.expiresAt).toLocaleString() : 'unknown'}</div></div><button onClick={() => revoke(session.id)} disabled={busy === session.id} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-red-500/20 px-4 text-xs font-semibold text-red-700 hover:bg-red-500/5 dark:text-red-300">{busy === session.id ? <Spinner className="h-4 w-4 animate-spin" /> : <XCircle className="h-4 w-4" />}Revoke</button></div>; })}{sessions.length === 0 && <div className="p-10 text-center text-sm text-foreground-muted">No active verified sessions.</div>}</div>}</section></div></AdminLayout>;
}
