'use client';
import { useCallback, useEffect, useState } from 'react';
import { Download, FileSpreadsheet, RefreshCw } from 'lucide-react';
import { AdminLayout } from '@/components/admin/admin-layout';
import { Spinner } from '@/components/design/primitives';
import { auth } from '@/lib/firebase';
import { onAuthChange } from '@/lib/auth';

export default function ReportsPage() {
  const [summary, setSummary] = useState<any>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(''); const [error, setError] = useState('');
  const token = useCallback(async () => { const user = auth.currentUser; if (!user) throw new Error('Your admin session has expired.'); return user.getIdToken(); }, []);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch('/api/admin/reports?report=summary', { headers: { Authorization: `Bearer ${await token()}` }, cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSummary(data); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load reports.'); } finally { setLoading(false); } }, [token]);
  useEffect(() => onAuthChange(user => { if (user) load(); else setLoading(false); }), [load]);
  const download = async (report: string) => { setWorking(report); try { const response = await fetch(`/api/admin/reports?report=${report}`, { headers: { Authorization: `Bearer ${await token()}` } }); if (!response.ok) throw new Error((await response.json()).error); const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = `auronix-${report}.csv`; link.click(); URL.revokeObjectURL(url); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Export failed.'); } finally { setWorking(''); } };
  return <AdminLayout><div className="space-y-6"><header className="ac-workspace-hero"><div><span className="ac-eyebrow"><FileSpreadsheet className="h-4 w-4" /> Operations intelligence</span><h1>Reports & exports</h1><p>Download current partner, seller-application, and supplier records for controlled business analysis.</p></div><button className="ac-button ac-button-secondary" onClick={load}><RefreshCw className="h-4 w-4" />Refresh</button></header>{error && <div className="ac-alert ac-alert-error">{error}</div>}{loading ? <div className="ac-content-panel flex min-h-[300px] items-center justify-center"><Spinner className="h-7 w-7" /></div> : <><div className="ac-report-kpis">{Object.entries(summary?.totals || {}).map(([label, value]) => <article className="ac-content-panel" key={label}><span>{label.replace(/([A-Z])/g, ' $1')}</span><strong>{String(value)}</strong></article>)}</div><section className="ac-content-panel p-6"><h2 className="text-xl font-semibold">Exportable records</h2><p className="mt-1 text-sm text-foreground-muted">Exports are generated from live authorized records and recorded in the security audit.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{[['partners', 'Partners', 'Account, business, application, and current commercial profile.'], ['applications', 'Applications', 'Full application index including status, revision, and timestamps.'], ['suppliers', 'Suppliers', 'Supplier contacts, categories, terms, and review status.']].map(([id, title, description]) => <article className="ac-export-card" key={id}><FileSpreadsheet className="h-6 w-6" /><h3>{title}</h3><p>{description}</p><button onClick={() => download(id)} disabled={!!working}>{working === id ? <Spinner className="h-4 w-4" /> : <Download className="h-4 w-4" />}Export CSV</button></article>)}</div></section></>}</div></AdminLayout>;
}
