'use client';
import { useEffect, useMemo, useState } from 'react';
import { RefreshCw, Search, ScrollText, ShieldAlert } from 'lucide-react';
import { AdminLayout } from '@/components/admin/admin-layout';
import { Spinner } from '@/components/design/primitives';
import { auth } from '@/lib/firebase';
import { onAuthChange } from '@/lib/auth';

export default function AuditPage() {
  const [entries, setEntries] = useState<any[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [query, setQuery] = useState(''); const [source, setSource] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/admin/activity', { headers: { Authorization: `Bearer ${token}` }, cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setEntries(data.activity || []); setCounts(data.counts || {}); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load activity.'); } finally { setLoading(false); } };
  useEffect(() => onAuthChange(user => { if (user) load(); else setLoading(false); }), []);
  const filtered = useMemo(() => entries.filter(item => (source === 'all' || item.source === source) && `${item.action} ${item.actorEmail} ${item.targetType} ${item.targetId} ${item.summary} ${item.ipHash} ${item.userAgent}`.toLowerCase().includes(query.toLowerCase())), [entries, query, source]);
  return <AdminLayout><div className="space-y-6"><header className="ac-workspace-hero"><div><span className="ac-eyebrow"><ScrollText className="h-4 w-4" /> Security & operations</span><h1>Activity history</h1><p>A read-only, server-authorized history of admin actions, security sessions, operational changes, and system errors.</p></div><button className="ac-button ac-button-secondary" onClick={load}><RefreshCw className="h-4 w-4" />Refresh</button></header>{error && <div className="ac-alert ac-alert-error"><ShieldAlert className="h-4 w-4" />{error}</div>}{loading ? <div className="ac-content-panel flex min-h-[320px] items-center justify-center"><Spinner className="h-7 w-7" /></div> : <><div className="ac-audit-filters"><label><Search className="h-4 w-4" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Action, actor, target, IP hash…" /></label><div>{['all', 'admin', 'operations', 'security', 'errors'].map(value => <button key={value} className={source === value ? 'is-active' : ''} onClick={() => setSource(value)}>{value} {value !== 'all' && <small>{counts[value] || 0}</small>}</button>)}</div></div><section className="ac-content-panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1020px] text-left text-sm"><thead><tr><th>Time</th><th>Source</th><th>Action</th><th>Actor</th><th>Target</th><th>Summary</th><th>Security context</th></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td className="whitespace-nowrap">{item.createdAt ? new Date(item.createdAt).toLocaleString() : '—'}</td><td><span className="ac-source-pill" data-source={item.source}>{item.source}</span></td><td className="font-mono text-xs font-semibold">{item.action || 'UNKNOWN'}</td><td>{item.actorEmail || 'system'}</td><td><div>{item.targetType || '—'}</div><small>{item.targetId || ''}</small></td><td className="max-w-md">{item.summary || '—'}</td><td><small>{item.ipHash ? `IP ${item.ipHash.slice(0, 12)}…` : 'No IP'}<br />{String(item.userAgent || '').slice(0, 45)}</small></td></tr>)}</tbody></table>{!filtered.length && <p className="p-10 text-center text-sm text-foreground-muted">No matching activity records.</p>}</div></section></>}</div></AdminLayout>;
}
