'use client';
import { useEffect, useMemo, useState } from 'react';
import { onValue, ref } from 'firebase/database';
import { Search, ScrollText } from 'lucide-react';
import { AdminLayout } from '@/components/admin/admin-layout';
import { db } from '@/lib/firebase';

type Entry = { id: string; action?: string; actorEmail?: string; targetType?: string; targetId?: string; summary?: string; createdAt?: number };
export default function AuditPage() {
  const [entries, setEntries] = useState<Entry[]>([]); const [query, setQuery] = useState('');
  useEffect(() => { const cleanups = [onValue(ref(db, 'adminAuditLogs'), snapshot => { const items = snapshot.exists() ? Object.entries(snapshot.val() as Record<string, Omit<Entry, 'id'>>).map(([id, value]) => ({ ...value, id })) : []; setEntries(current => [...current.filter(item => !item.id.startsWith('admin:')), ...items.map(item => ({ ...item, id: `admin:${item.id}` }))].sort((a, b) => Number(b.createdAt || 0) - Number(a.createdAt || 0)).slice(0, 1000)); }), onValue(ref(db, 'siteOperationsAudit'), snapshot => { const items = snapshot.exists() ? Object.entries(snapshot.val() as Record<string, any>).map(([id, value]) => ({ ...value, id: `operations:${id}`, actorEmail: value.updatedBy || 'system', targetType: 'siteOperation', summary: value.reason || value.path || '' })) : []; setEntries(current => [...current.filter(item => !item.id.startsWith('operations:')), ...items].sort((a, b) => Number(b.createdAt || 0) - Number(a.createdAt || 0)).slice(0, 1000)); })]; return () => cleanups.forEach(fn => fn()); }, []);
  const filtered = useMemo(() => entries.filter(item => `${item.action} ${item.actorEmail} ${item.targetType} ${item.targetId} ${item.summary}`.toLowerCase().includes(query.toLowerCase())), [entries, query]);
  return <AdminLayout><div className="space-y-6"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-accent"><ScrollText className="h-4 w-4" />Security & operations</div><h1 className="mt-3 text-3xl font-semibold tracking-tight">Admin Audit Logs</h1><p className="mt-2 text-sm text-foreground-muted">A read-only record of important administrative and automatic operational actions.</p></div><label className="relative block max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-foreground-muted" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search action, admin, target, or summary…" className="h-11 w-full ac-content-panel pl-10 pr-4 text-sm outline-none focus:border-accent" /></label><div className="overflow-hidden ac-content-panel"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-secondary/50 text-xs uppercase tracking-wider text-foreground-muted"><tr><th className="px-5 py-3">Time</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Actor</th><th className="px-5 py-3">Target</th><th className="px-5 py-3">Summary</th></tr></thead><tbody className="divide-y divide-border">{filtered.map(item => <tr key={item.id}><td className="whitespace-nowrap px-5 py-4 text-foreground-muted">{item.createdAt ? new Date(item.createdAt).toLocaleString() : '—'}</td><td className="px-5 py-4 font-mono text-xs font-semibold">{item.action || 'UNKNOWN'}</td><td className="px-5 py-4">{item.actorEmail || 'system'}</td><td className="px-5 py-4"><div>{item.targetType || '—'}</div><div className="max-w-[180px] truncate text-xs text-foreground-muted">{item.targetId}</div></td><td className="max-w-md px-5 py-4 text-foreground-muted">{item.summary || '—'}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-10 text-center text-sm text-foreground-muted">No matching audit entries.</div>}</div></div></div></AdminLayout>;
}
